Test ng hw1
Olga-Girinskaya/TAF pull request #2
Opened 2022-04-22 21:31 UTC by Olga-Girinskaya

2022-04-25 11:43 UTC, wildpioneer requested changes

2022-04-25 11:43 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public double div(double a, double b) {
А для чего ты удалила метод sum?

2022-04-25 11:43 UTC, wildpioneer commented on src/test/java/TestDouble.java
> +    // protected Calculator calculator = new Calculator("Test calculator");
Перед отправкой на проверку - всегда удаляй не нужный код

2022-04-25 11:43 UTC, wildpioneer commented on src/test/java/TestDouble.java
> +        Assert.assertEquals(calculator.div(4.5, 3), 1.5, "Неверный ответ....");
Сообщение в ошибке должно быть более информативным

2022-04-25 11:43 UTC, wildpioneer commented on src/test/java/TestDouble.java
> +    public void testDivDouble1() {
Название тестовых методов - переделать согласно https://dzone.com/articles/7-popular-unit-test-naming

2022-05-05 17:16 UTC, Olga-Girinskaya commented
Исправлено

2022-05-05 17:16 UTC, Olga-Girinskaya commented on src/main/java/Calculator.java
> +    public double div(double a, double b) {
Метод sum удалила, так как в домашней работе он не используется, но не обратила внимание, что лишние классы, относящиеся к методу sum, не удалились.

2022-05-30 10:54 UTC, wildpioneer commented
проверено

2022-05-30 10:54 UTC, closed without merging